### ISSUE TITLE
New logo

### ISSUE THREAD

**Issue by AvramRobert** [AvramRobert/omnia#32]
We need a new proper logo. 

Conceptually it should remain the same:
A lambda embedded into an omega.

**Comment by ngeshlew** [comment]
I can be able to tackle this @AvramRobert. Is it an open source project?

**Comment by AvramRobert** [comment]
Well hello @ngeshlew!

That's very kind of you.
It is indeed an open source project.

**Comment by AvramRobert** [comment]
Solved.
