### ISSUE TITLE
Load spike on idle

### ISSUE THREAD

**Issue by rpompen** [AvramRobert/omnia#4]
Thanks for a great REPL, Robert!

On my Ubuntu LTS 18.04 derivative with openjdk 8 I see a 100% CPU load from the moment I start omnia. It doesn't seem to settle over time.

Regards,

Roel Pompen

**Comment by AvramRobert** [comment]
Hello Roel!

Thank you for the issue!
I luckily know of this problem and its cause is rather annoying.
I've released a new version of omnia (0.2.1) that should've fixed it.
Please do give it a try and tell me if you still notice the problem. :)

Cheers,
Robert

**Comment by rpompen** [comment]
Thanks! That fixed it.
